version: "3.8"
services:
  web:
    build: ./app
    image: 276477552161.dkr.ecr.us-east-2.amazonaws.com/project:project_web
    command: gunicorn favorite_cocktails.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=favorite_cocktails_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=project.ctn50tzo8hcy.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-13-90-136.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 276477552161.dkr.ecr.us-east-2.amazonaws.com/project:project_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
